//
//  LoginWithFacebookModels.swift
//  MyProject
//
//  Created by Everton Cunha on 10/12/17.
//  Copyright (c) 2017 EPC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoginWithFacebook
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
      // facebook app id
    }
    struct Response
    {
      // facebook user details
    }
    struct ViewModel
    {
      // stuff for UI
    }
  }
}
