//
//  LoginWithFacebookPresenter.swift
//  MyProject
//
//  Created by Everton Cunha on 10/12/17.
//  Copyright (c) 2017 EPC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginWithFacebookPresentationLogic
{
  func presentSomething(response: LoginWithFacebook.Something.Response)
}

class LoginWithFacebookPresenter: LoginWithFacebookPresentationLogic
{
  weak var viewController: LoginWithFacebookDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: LoginWithFacebook.Something.Response)
  {
    let viewModel = LoginWithFacebook.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
