//
//  LoginWithFacebookInteractor.swift
//  MyProject
//
//  Created by Everton Cunha on 10/12/17.
//  Copyright (c) 2017 EPC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginWithFacebookBusinessLogic
{
  func doSomething(request: LoginWithFacebook.Something.Request)
}

protocol LoginWithFacebookDataStore
{
  //var name: String { get set }
}

class LoginWithFacebookInteractor: LoginWithFacebookBusinessLogic, LoginWithFacebookDataStore
{
  var presenter: LoginWithFacebookPresentationLogic?
  var worker: LoginWithFacebookWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LoginWithFacebook.Something.Request)
  {
    worker = LoginWithFacebookWorker()
    worker?.doSomeWork()
    
    let response = LoginWithFacebook.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
